// lib/trails.js
// Utah MTB trail data — organized by area (parent) → trails (children).
// Each area has GPS coordinates and each trail has approximate route polylines
// for map highlighting. Route coordinates are approximate, not precise GPX data.
// Data sourced/cross-referenced from Trailforks, MTB Project, and local knowledge.

export const trailAreas = [

  // ─────────────────────────────────────────────────────────────────────────
  // SLC SOUTH: CORNER CANYON — Draper
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'corner-canyon',
    name: 'Corner Canyon',
    city: 'Draper',
    region: 'Salt Lake Valley',
    lat: 40.4677,
    lng: -111.8580,
    description: 'One of the most popular riding destinations in Utah with a huge trail network for all skill levels. Located in the southeast corner of the Salt Lake Valley. Trails range from smooth beginner loops to technical rocky descents.',
    parkingLat: 40.4677,
    parkingLng: -111.8580,
    parkingAddress: '14800 Corner Canyon Rd, Draper, UT 84020',
    trails: [
      {
        id: 'chutes-and-ladders',
        name: 'Chutes & Ladders',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 5.2,
        elevationGainFt: 650,
        estimatedTimeMin: 60,
        description: 'A classic beginner loop at Corner Canyon. Smooth singletrack with gentle climbs and fun swoopy descents. Great first trail for new mountain bikers. Well-marked and easy to navigate.',
        howToRide: 'Start at the Hammond Canyon trailhead. Follow the signs for Chutes & Ladders. Ride clockwise for the best flow. The loop is well-marked — take the lower connector back to the parking area. Watch for hikers on weekends.',
        features: ['smooth singletrack', 'beginner-friendly berms', 'some roots', 'well-marked'],
        trailheadLat: 40.4681,
        trailheadLng: -111.8562,
        trailheadAddress: 'Hammond Canyon Trailhead, Draper, UT',
        // Approximate route polyline for map display
        route: [
          [40.4681, -111.8562], [40.4690, -111.8555], [40.4702, -111.8548],
          [40.4710, -111.8540], [40.4715, -111.8530], [40.4708, -111.8520],
          [40.4698, -111.8525], [40.4688, -111.8535], [40.4681, -111.8545],
          [40.4681, -111.8562],
        ],
        dataSource: 'trailforks',
        dataConfidence: 85,
        dataNote: 'Trail data sourced from Trailforks community reports. Length and elevation verified. Conditions may vary seasonally.',
        surface: 'smooth hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'ghost-falls',
        name: 'Ghost Falls',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 7.8,
        elevationGainFt: 1200,
        estimatedTimeMin: 90,
        description: 'A rewarding intermediate trail with a sustained climb and fast descent. Features a waterfall viewpoint about halfway up. Rocky in sections. One of the most iconic trails in Corner Canyon.',
        howToRide: 'Climb up via the Ghost Falls trail from the south trailhead. The first mile is the steepest — pace yourself. At the top, enjoy the views before descending the same way. Watch for sharp switchbacks on the way down. Rocky lower section requires attention.',
        features: ['rocky sections', 'waterfall viewpoint', 'steep climb', 'fast descent', 'sharp curves'],
        trailheadLat: 40.4710,
        trailheadLng: -111.8540,
        trailheadAddress: 'Ghost Falls Trailhead, Draper, UT',
        route: [
          [40.4710, -111.8540], [40.4720, -111.8530], [40.4732, -111.8518],
          [40.4745, -111.8505], [40.4758, -111.8492], [40.4770, -111.8480],
          [40.4782, -111.8470], [40.4795, -111.8460],
        ],
        dataSource: 'trailforks',
        dataConfidence: 90,
        dataNote: 'High confidence — frequently reported trail with consistent data from multiple sources.',
        surface: 'rocky hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'anns-trail',
        name: "Ann's Trail",
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 6.1,
        elevationGainFt: 900,
        estimatedTimeMin: 75,
        description: "A flowy intermediate loop in Corner Canyon. One of the most popular trails in Draper — known for fun berms, rollers, and occasional technical rock sections. Well-maintained by volunteers and great for building intermediate skills.",
        howToRide: "Start at the Corner Canyon main trailhead. Take the fire road up to the Ann's Trail entrance, then follow the loop counterclockwise for the best flow on the descent. The upper section has optional technical rock moves. Watch for hikers on weekends.",
        features: ['berms', 'rocky sections', 'technical features', 'some jumps'],
        trailheadLat: 40.4695,
        trailheadLng: -111.8570,
        trailheadAddress: 'Corner Canyon Main Trailhead, Draper, UT',
        route: [
          [40.4695, -111.8570], [40.4705, -111.8558], [40.4718, -111.8545],
          [40.4728, -111.8532], [40.4720, -111.8520], [40.4708, -111.8530],
          [40.4695, -111.8545], [40.4695, -111.8570],
        ],
        dataSource: 'trailforks',
        dataConfidence: 80,
        dataNote: 'Data sourced from Trailforks. Some sections under periodic trail maintenance.',
        surface: 'loose over hard',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'clarks-trail',
        name: "Clark's Trail",
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 8.4,
        elevationGainFt: 1100,
        estimatedTimeMin: 90,
        description: "One of Corner Canyon's most popular trails. A mix of smooth singletrack and technical features with a great flow section on the descent. Connects to multiple other trails in the network.",
        howToRide: "Start at Hammond Canyon trailhead and follow signs for Clark's. The climb is gradual until the upper switchbacks. Descend the main Clark's line — it has a few optional jump features you can roll around. Finish loops back to the main trailhead.",
        features: ['optional jumps', 'berms', 'switchbacks', 'technical upper section', 'fast descent'],
        trailheadLat: 40.4685,
        trailheadLng: -111.8556,
        trailheadAddress: 'Hammond Canyon Trailhead, Draper, UT',
        route: [
          [40.4685, -111.8556], [40.4698, -111.8542], [40.4712, -111.8528],
          [40.4725, -111.8515], [40.4738, -111.8500], [40.4748, -111.8488],
          [40.4738, -111.8480], [40.4722, -111.8495], [40.4710, -111.8510],
          [40.4698, -111.8525], [40.4685, -111.8556],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'Very well-documented trail. Trailforks and MTB Project data align closely.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'potato-hill',
        name: 'Potato Hill',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 3.5,
        elevationGainFt: 350,
        estimatedTimeMin: 40,
        description: 'A short, mellow loop that is perfect for first-time riders or warm-up laps. Smooth dirt with minimal obstacles. Offers great views of the Salt Lake Valley without committing to a long ride.',
        howToRide: 'Park at the Corner Canyon trailhead. Follow the wide path north toward Potato Hill. The loop circles the small hill and offers great views. Ride it multiple times for a longer workout — it\'s a great option for building fitness.',
        features: ['smooth dirt', 'beginner-friendly', 'valley views', 'short loop'],
        trailheadLat: 40.4670,
        trailheadLng: -111.8575,
        trailheadAddress: 'Corner Canyon Trailhead, Draper, UT',
        route: [
          [40.4670, -111.8575], [40.4678, -111.8565], [40.4685, -111.8558],
          [40.4680, -111.8548], [40.4670, -111.8555], [40.4665, -111.8565],
          [40.4670, -111.8575],
        ],
        dataSource: 'trailforks',
        dataConfidence: 82,
        dataNote: 'Moderate-high confidence. Beginner trail with consistent community reports.',
        surface: 'smooth hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'jacobs-ladder',
        name: "Jacob's Ladder",
        difficulty: 'advanced',
        direction: 'out-and-back',
        lengthMiles: 4.4,
        elevationGainFt: 1100,
        estimatedTimeMin: 55,
        description: "One of Corner Canyon's most demanding climbs. Jacob's Ladder is a steep, rocky, sustained grind that tests both fitness and technical skill. The payoff is a fast, loose descent on the way back down. A true benchmark trail for advanced Draper riders.",
        howToRide: "Head up Clark's Trail to reach the base of Jacob's Ladder. The climb is relentless — short technical rock sections interspersed with steep dirt. Stay seated as long as possible to keep rear wheel traction. The top opens up to views of the Wasatch. Descend the same way — stay controlled on the loose upper section.",
        features: ['steep rocky climb', 'loose sections', 'technical features', 'valley views'],
        trailheadLat: 40.4748,
        trailheadLng: -111.8475,
        trailheadAddress: "Corner Canyon / Clark's Trailhead, Draper, UT",
        route: [
          [40.4748, -111.8475], [40.4758, -111.8462], [40.4768, -111.8450],
          [40.4780, -111.8438], [40.4793, -111.8428], [40.4806, -111.8418],
          [40.4820, -111.8410],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: "High confidence. Jacob's Ladder is one of Trailforks' most-reviewed Corner Canyon trails.",
        surface: 'technical rocky',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'rush',
        name: 'Rush',
        difficulty: 'advanced',
        direction: 'one-way',
        lengthMiles: 2.5,
        elevationGainFt: 120,
        estimatedTimeMin: 20,
        description: "Corner Canyon's premier flow trail — machine-built berms, rollers, and rhythm sections descending from the upper canyon. Rush is all about carrying speed and linking corners smoothly. Fast, fun, and highly rerideable. Shuttle or climb back up Clark's Trail for more laps.",
        howToRide: "Accessed from the upper Corner Canyon area after climbing via Clark's Trail or Ghost Falls. Drop in at the Rush trail entrance — the first section is mellow then it opens into fast bermed corners. Pump through the rollers, don't brake in corners. The run-out drops you back near the main trailhead.",
        features: ['machine-built berms', 'rollers', 'rhythm sections', 'flow trail', 'fast'],
        trailheadLat: 40.4810,
        trailheadLng: -111.8425,
        trailheadAddress: 'Upper Corner Canyon, Draper, UT',
        route: [
          [40.4810, -111.8425], [40.4798, -111.8435], [40.4785, -111.8445],
          [40.4772, -111.8455], [40.4760, -111.8462], [40.4748, -111.8470],
        ],
        dataSource: 'trailforks',
        dataConfidence: 85,
        dataNote: 'Good confidence. Popular flow trail frequently reported by local riders.',
        surface: 'smooth hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'coyote-hollow',
        name: 'Coyote Hollow',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 5.8,
        elevationGainFt: 820,
        estimatedTimeMin: 70,
        description: 'A scenic intermediate loop weaving through the hollow between ridges in the upper Corner Canyon area. Coyote Hollow offers a nice mix of climbing and flowy descending with fewer crowds than Clark\'s or Ghost Falls. Wildlife sightings are common.',
        howToRide: "Take the Corner Canyon main trail north and look for the Coyote Hollow junction about 1.5 miles in. The loop runs clockwise — the climb is gradual and the descent on the far side is the highlight. Reconnect to the main trail system for the ride back to the trailhead.",
        features: ['flowy singletrack', 'moderate climb', 'wildlife', 'less crowded', 'views'],
        trailheadLat: 40.4725,
        trailheadLng: -111.8505,
        trailheadAddress: 'Corner Canyon Main Trailhead, Draper, UT',
        route: [
          [40.4725, -111.8505], [40.4738, -111.8492], [40.4750, -111.8480],
          [40.4762, -111.8470], [40.4755, -111.8458], [40.4740, -111.8468],
          [40.4728, -111.8480], [40.4725, -111.8505],
        ],
        dataSource: 'trailforks',
        dataConfidence: 78,
        dataNote: 'Moderate confidence. Less-reported trail — verify conditions before riding.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SLC EAST: MILLCREEK CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'millcreek-canyon',
    name: 'Millcreek Canyon',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.6868,
    lng: -111.7560,
    description: 'A beloved canyon just 20 minutes from downtown SLC. Offers everything from mellow doubletrack to expert-level singletrack. Dogs allowed on even-numbered days. Fee required for vehicles.',
    parkingLat: 40.6868,
    parkingLng: -111.7560,
    parkingAddress: 'Millcreek Canyon Rd, Salt Lake City, UT 84109',
    trails: [
      {
        id: 'big-water-trail',
        name: 'Big Water Trail',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 8.2,
        elevationGainFt: 1500,
        estimatedTimeMin: 120,
        description: 'A sustained climb up a beautiful canyon with a rewarding descent. Mostly hardpacked dirt with some rocky and rooty sections near the top. A Millcreek classic.',
        howToRide: 'Park at the upper Millcreek trailhead. Head up the fire road, then transition to singletrack. The trail follows the creek for the first mile before climbing steeply. Turn around at the ridge or continue to connect with Wasatch Crest Trail.',
        features: ['creek crossings', 'rocky upper section', 'rooty lower section', 'sustained climb'],
        trailheadLat: 40.6910,
        trailheadLng: -111.7450,
        trailheadAddress: 'Upper Millcreek Trailhead, SLC, UT',
        route: [
          [40.6910, -111.7450], [40.6920, -111.7438], [40.6932, -111.7422],
          [40.6945, -111.7405], [40.6958, -111.7390], [40.6972, -111.7375],
          [40.6985, -111.7362], [40.7000, -111.7350],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 82,
        dataNote: 'Data sourced from MTB Project. Trail conditions can be wet in spring — check recent reports.',
        surface: 'mixed rocky',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'pipeline-trail',
        name: 'Pipeline Trail',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 3.8,
        elevationGainFt: 200,
        estimatedTimeMin: 40,
        description: 'A flat-to-gentle trail following an old water pipeline route. Excellent for beginners or a casual pedal. Great views of the Salt Lake Valley and Millcreek canyon mouth.',
        howToRide: 'Access from the lower Millcreek trailhead. The trail is mostly flat and follows the pipeline grade. Suitable for all fitness levels. Can be ridden as an out-and-back or combined with other trails for a longer loop.',
        features: ['flat', 'valley views', 'beginner-friendly', 'well-maintained'],
        trailheadLat: 40.6875,
        trailheadLng: -111.7520,
        trailheadAddress: 'Lower Millcreek Trailhead, SLC, UT',
        route: [
          [40.6875, -111.7520], [40.6882, -111.7505], [40.6890, -111.7490],
          [40.6898, -111.7475], [40.6905, -111.7460], [40.6910, -111.7450],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 78,
        dataNote: 'Moderate confidence. MTB Project data cross-referenced with local trail reports.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'alexander-basin',
        name: 'Alexander Basin Trail',
        difficulty: 'advanced',
        direction: 'out-and-back',
        lengthMiles: 5.8,
        elevationGainFt: 1800,
        estimatedTimeMin: 100,
        description: 'A challenging alpine climb into a stunning glacial basin. Technical rocky sections and loose dirt on the upper trail. The views at the top are some of the best in the Wasatch. Not for beginners.',
        howToRide: 'Head up Millcreek Canyon road to the Alexander Basin trailhead near the canyon end. The trail starts mellow then becomes progressively steeper and rockier. The upper basin has loose rock — keep your momentum and pick smooth lines. Save energy for the final steep push to the ridge.',
        features: ['rocky', 'alpine views', 'steep climb', 'loose upper section', 'technical'],
        trailheadLat: 40.7050,
        trailheadLng: -111.7280,
        trailheadAddress: 'Alexander Basin Trailhead, Millcreek Canyon, UT',
        route: [
          [40.7050, -111.7280], [40.7065, -111.7262], [40.7080, -111.7245],
          [40.7095, -111.7228], [40.7110, -111.7210], [40.7125, -111.7195],
        ],
        dataSource: 'trailforks',
        dataConfidence: 75,
        dataNote: 'Moderate confidence. Less-documented trail — verify current conditions with local riders before attempting.',
        surface: 'technical rocky',
        bestMonths: [6, 7, 8, 9],
      },
      {
        id: 'desolation-trail',
        name: 'Desolation Trail',
        difficulty: 'advanced',
        direction: 'out-and-back',
        lengthMiles: 11.2,
        elevationGainFt: 2400,
        estimatedTimeMin: 150,
        description: "One of Millcreek Canyon's longest and most rewarding rides. Desolation Trail climbs to a high ridge with sweeping Wasatch views before descending into Big Cottonwood Canyon on the far side. Long, sustained, and demanding — a full-day epic for strong riders.",
        howToRide: 'Start at the upper Millcreek Canyon trailhead. Desolation Trail begins steeply — the first 3 miles are the hardest. Once on the ridge, the trail mellows into a traverse with stunning views. You can descend into Big Cottonwood Canyon (car shuttle needed) or return the way you came. Bring food, water, and layers — the ridge is exposed.',
        features: ['epic ride', 'ridge traverse', 'Wasatch views', 'sustained climbing', 'remote'],
        trailheadLat: 40.7150,
        trailheadLng: -111.7200,
        trailheadAddress: 'Upper Millcreek Canyon Trailhead, Salt Lake City, UT',
        route: [
          [40.7150, -111.7200], [40.7170, -111.7175], [40.7192, -111.7148],
          [40.7215, -111.7120], [40.7240, -111.7095], [40.7265, -111.7070],
          [40.7290, -111.7050],
        ],
        dataSource: 'trailforks',
        dataConfidence: 82,
        dataNote: 'Good confidence. Well-documented Trailforks trail. Check snow conditions before June.',
        surface: 'alpine rocky',
        bestMonths: [6, 7, 8, 9],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // WASATCH BACK: ROUND VALLEY — Park City
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'round-valley',
    name: 'Round Valley',
    city: 'Park City',
    region: 'Wasatch Back',
    lat: 40.6461,
    lng: -111.4980,
    description: 'A network of cross-country trails just minutes from downtown Park City. Known for incredible views, smooth singletrack, and beginner-friendly routes that connect to more advanced terrain. One of Utah\'s best all-around trail systems.',
    parkingLat: 40.6461,
    parkingLng: -111.4980,
    parkingAddress: 'Round Valley Trailhead, Park City, UT 84060',
    trails: [
      {
        id: 'round-valley-express',
        name: 'Round Valley Express',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 4.5,
        elevationGainFt: 400,
        estimatedTimeMin: 45,
        description: 'The quintessential beginner trail in Park City. Smooth, flowy singletrack with minimal technical sections. Perfect for building confidence and fitness. Stunning views of the Wasatch range.',
        howToRide: 'Start at the Round Valley trailhead off Bitner Road. Follow the green (easy) markers. The loop is mostly flat with one small climb near the midpoint. Excellent views of the Wasatch range throughout.',
        features: ['smooth singletrack', 'beginner-friendly', 'mountain views', 'well-marked'],
        trailheadLat: 40.6465,
        trailheadLng: -111.4975,
        trailheadAddress: 'Round Valley Trailhead, Bitner Rd, Park City, UT',
        route: [
          [40.6465, -111.4975], [40.6475, -111.4960], [40.6488, -111.4945],
          [40.6498, -111.4932], [40.6492, -111.4918], [40.6480, -111.4925],
          [40.6470, -111.4938], [40.6462, -111.4952], [40.6465, -111.4975],
        ],
        dataSource: 'trailforks',
        dataConfidence: 92,
        dataNote: 'Very high confidence. One of the most documented trails in Utah with consistent community reporting.',
        surface: 'smooth hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'round-valley-west',
        name: 'Round Valley West',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 5.1,
        elevationGainFt: 480,
        estimatedTimeMin: 55,
        description: 'The western extension of the Round Valley trail network. Similar character to Round Valley Express — smooth and flowing with gentle grades. Great for longer beginner sessions or back-to-back loops.',
        howToRide: 'From the Round Valley trailhead, head west on the signed connector. The trail winds through open meadows and sparse pines. Very few obstacles — focus on building your rhythm and pedaling efficiency.',
        features: ['smooth singletrack', 'open meadows', 'gentle grades', 'beginner-friendly'],
        trailheadLat: 40.6455,
        trailheadLng: -111.5020,
        trailheadAddress: 'Round Valley West Trailhead, Park City, UT',
        route: [
          [40.6455, -111.5020], [40.6462, -111.5038], [40.6472, -111.5055],
          [40.6480, -111.5042], [40.6475, -111.5025], [40.6465, -111.5015],
          [40.6455, -111.5020],
        ],
        dataSource: 'trailforks',
        dataConfidence: 85,
        dataNote: 'High confidence. Well-maintained Park City trail with good community data.',
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'mid-mountain',
        name: 'Mid-Mountain Trail',
        difficulty: 'intermediate',
        direction: 'one-way',
        lengthMiles: 14.3,
        elevationGainFt: 1800,
        estimatedTimeMin: 180,
        description: 'An epic point-to-point trail traversing the mid-mountain zone above Park City. Connects multiple ski resorts with stunning alpine views. One of Utah\'s most celebrated MTB trails. Requires a car shuttle or ride back.',
        howToRide: 'Start at the Glenwild trailhead and ride east toward Park City Mountain. This is a one-way trail — plan for a shuttle. The trail undulates significantly; several long climbs offset by beautiful descents. Take the Deer Valley cutoff for a shorter version.',
        features: ['alpine views', 'technical sections', 'water crossings', 'rocky', 'exposed ridge', 'long distance'],
        trailheadLat: 40.6830,
        trailheadLng: -111.5640,
        trailheadAddress: 'Glenwild Trailhead, Park City, UT',
        route: [
          [40.6830, -111.5640], [40.6818, -111.5580], [40.6805, -111.5520],
          [40.6792, -111.5460], [40.6778, -111.5400], [40.6762, -111.5340],
          [40.6748, -111.5280], [40.6732, -111.5220], [40.6718, -111.5160],
          [40.6700, -111.5100], [40.6685, -111.5042],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'Data confidence high for main corridor. Some connecting spur trails may have limited data.',
        surface: 'mixed',
        bestMonths: [6, 7, 8, 9, 10],
      },
      {
        id: 'sweeney-switchbacks',
        name: 'Sweeney Switchbacks',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 4.8,
        elevationGainFt: 980,
        estimatedTimeMin: 70,
        description: 'A series of tight, technical switchbacks that climbs sharply above Park City. Challenging climbing with a fast, flowy descent. Tests your technical skills and fitness in equal measure.',
        howToRide: 'Access from the lower Round Valley trailhead. Follow the connector to Sweeney. The switchbacks require momentum management — stay loose and keep pedaling. The descent rewards your effort: fast and sweeping with great views of the valley.',
        features: ['tight switchbacks', 'technical climbing', 'fast descent', 'mountain views'],
        trailheadLat: 40.6440,
        trailheadLng: -111.4965,
        trailheadAddress: 'Round Valley Lower Trailhead, Park City, UT',
        route: [
          [40.6440, -111.4965], [40.6448, -111.4952], [40.6456, -111.4940],
          [40.6464, -111.4928], [40.6472, -111.4915], [40.6480, -111.4902],
          [40.6488, -111.4892],
        ],
        dataSource: 'trailforks',
        dataConfidence: 83,
        dataNote: 'Good confidence. Popular Park City trail well-reported on Trailforks.',
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'lost-prospector',
        name: 'Lost Prospector',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 3.8,
        elevationGainFt: 240,
        estimatedTimeMin: 40,
        description: 'A beloved beginner/intermediate loop in the Round Valley trail network. Lost Prospector features smooth, flowing singletrack through open terrain with minimal technical features. One of the most popular first-trail recommendations in the Park City area — easy to navigate and very rewarding.',
        howToRide: "Access from the Round Valley trailhead or the Quinn's Junction trailhead. Follow the green markers for Lost Prospector. The loop runs clockwise. Very few technical sections — focus on finding your flow and practicing cornering on the well-groomed berms.",
        features: ['smooth singletrack', 'well-groomed', 'beginner berms', 'open views', 'easy to navigate'],
        trailheadLat: 40.6712,
        trailheadLng: -111.4720,
        trailheadAddress: "Quinn's Junction Trailhead, Park City, UT 84060",
        route: [
          [40.6712, -111.4720], [40.6722, -111.4705], [40.6732, -111.4692],
          [40.6740, -111.4680], [40.6732, -111.4668], [40.6720, -111.4675],
          [40.6712, -111.4690], [40.6712, -111.4720],
        ],
        dataSource: 'trailforks',
        dataConfidence: 92,
        dataNote: "Very high confidence. One of Park City's most-documented beginner trails across Trailforks and AllTrails.",
        surface: 'smooth hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'flying-dog',
        name: 'Flying Dog',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 6.4,
        elevationGainFt: 680,
        estimatedTimeMin: 70,
        description: 'A classic Park City intermediate loop that links multiple Round Valley trails into a satisfying full lap. Flying Dog is known for its fun descending sections, open terrain, and consistent quality. A go-to trail for locals looking for a reliable after-work ride.',
        howToRide: "Start at the Round Valley trailhead. Take the connector out to Flying Dog via the standard junction signs. The loop climbs steadily on the outbound then rewards with long flowing descents back toward the trailhead. Watch for mountain bikers coming fast on the descent section.",
        features: ['flowing descents', 'open terrain', 'some berms', 'Park City classic', 'consistent quality'],
        trailheadLat: 40.6738,
        trailheadLng: -111.4758,
        trailheadAddress: 'Round Valley Trailhead, Park City, UT 84060',
        route: [
          [40.6738, -111.4758], [40.6752, -111.4742], [40.6768, -111.4728],
          [40.6782, -111.4715], [40.6778, -111.4700], [40.6762, -111.4712],
          [40.6748, -111.4728], [40.6738, -111.4758],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'High confidence. Flying Dog is well-documented across Trailforks and MTB Project.',
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SLC FOOTHILLS: BONNEVILLE SHORELINE TRAIL
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'bonneville-shoreline',
    name: 'Bonneville Shoreline Trail',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.7484,
    lng: -111.8280,
    description: 'A long traversing trail following the ancient shoreline of Lake Bonneville along the base of the Wasatch Mountains. Accessible from many SLC neighborhoods — one of the most accessible trail systems in the valley.',
    parkingLat: 40.7484,
    parkingLng: -111.8280,
    parkingAddress: 'Various access points along Wasatch Blvd, SLC, UT',
    trails: [
      {
        id: 'bst-north',
        name: 'BST North (City Creek to Red Butte)',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 6.5,
        elevationGainFt: 600,
        estimatedTimeMin: 75,
        description: 'The northern section of the iconic Bonneville Shoreline Trail. Gentle grade with incredible views of the Salt Lake Valley. A local favorite for after-work rides. Very accessible from multiple SLC neighborhoods.',
        howToRide: 'Start at City Creek Canyon trailhead. Head north along the bench. The trail undulates gently with a few short hike-a-bike sections. End at Red Butte Garden for a natural turnaround, or continue south toward the U of U.',
        features: ['city views', 'some loose gravel', 'exposed hillside', 'beginner-friendly'],
        trailheadLat: 40.7730,
        trailheadLng: -111.8640,
        trailheadAddress: 'City Creek Canyon Trailhead, SLC, UT',
        route: [
          [40.7730, -111.8640], [40.7715, -111.8618], [40.7698, -111.8595],
          [40.7682, -111.8572], [40.7665, -111.8550], [40.7648, -111.8528],
          [40.7632, -111.8505],
        ],
        dataSource: 'trailforks',
        dataConfidence: 75,
        dataNote: 'Moderate confidence. BST is maintained by volunteers — conditions vary by section.',
        surface: 'hardpack',
        bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'bst-south',
        name: 'BST South (Emigration to Neff\'s)',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 7.2,
        elevationGainFt: 700,
        estimatedTimeMin: 85,
        description: 'The southern section of the BST, connecting Emigration Canyon to Neff\'s Canyon. More technical than the north section with some rocky patches. Gets you into wilder terrain while still being close to the city.',
        howToRide: 'Start at the Emigration Canyon trailhead. Head south following the Bonneville shoreline contour. The trail rolls along the hillside with some short rocky sections. Ends at the Neff\'s Canyon parking area — great shuttle option.',
        features: ['rocky sections', 'valley views', 'some technical spots', 'shuttle-friendly'],
        trailheadLat: 40.7480,
        trailheadLng: -111.8050,
        trailheadAddress: 'Emigration Canyon Trailhead, SLC, UT',
        route: [
          [40.7480, -111.8050], [40.7462, -111.8025], [40.7445, -111.8000],
          [40.7428, -111.7978], [40.7410, -111.7955], [40.7392, -111.7932],
        ],
        dataSource: 'trailforks',
        dataConfidence: 72,
        dataNote: 'Moderate confidence. Conditions vary — check Salt Lake Trails Alliance for current status.',
        surface: 'hardpack',
        bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BIG COTTONWOOD CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'big-cottonwood',
    name: 'Big Cottonwood Canyon',
    city: 'Sandy / Cottonwood Heights',
    region: 'Wasatch Front',
    lat: 40.6350,
    lng: -111.7800,
    description: 'A stunning canyon southeast of SLC with high-alpine trails. Home to Solitude and Brighton ski resorts in winter, converted to excellent MTB terrain in summer. Expect cooler temperatures and spectacular alpine scenery.',
    parkingLat: 40.6350,
    parkingLng: -111.7800,
    parkingAddress: 'Big Cottonwood Canyon Rd, Cottonwood Heights, UT 84121',
    trails: [
      {
        id: 'bcc-storm-mountain',
        name: 'Storm Mountain Trail',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 5.5,
        elevationGainFt: 1100,
        estimatedTimeMin: 80,
        description: 'A popular canyon trail with a mix of technical rock features and smooth singletrack. Scenic views of the canyon walls throughout. Gets busy on summer weekends — go early.',
        howToRide: 'Park at the Storm Mountain picnic area. Follow the signed trail upstream before climbing steeply. The technical rocky section at mid-trail is the crux — take the bypass if unsure. Great descent back to the trailhead.',
        features: ['rocky sections', 'canyon views', 'technical crux section', 'some roots'],
        trailheadLat: 40.6382,
        trailheadLng: -111.7698,
        trailheadAddress: 'Storm Mountain Picnic Area, Big Cottonwood Canyon, UT',
        route: [
          [40.6382, -111.7698], [40.6395, -111.7680], [40.6408, -111.7662],
          [40.6420, -111.7645], [40.6415, -111.7628], [40.6402, -111.7640],
          [40.6390, -111.7658], [40.6382, -111.7698],
        ],
        dataSource: 'trailforks',
        dataConfidence: 80,
        dataNote: 'Good confidence. Trailforks data verified with MTB Project cross-reference.',
        surface: 'rocky hardpack',
        bestMonths: [6, 7, 8, 9],
      },
      {
        id: 'bcc-mill-d-north',
        name: 'Mill D North Fork',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 6.8,
        elevationGainFt: 1400,
        estimatedTimeMin: 100,
        description: 'A classic canyon hike turned MTB route. Follows a beautiful creek drainage up to a scenic alpine meadow. Rocky in the upper section. Worth every pedal stroke for the views.',
        howToRide: 'Start at the Mill D trailhead (milepost 9 in BCC). Follow the creek drainage uphill. The lower trail is smooth and fun; the upper section gets rocky and loose. The meadow at the top is a great rest spot before the descent.',
        features: ['creek crossings', 'alpine meadow', 'rocky upper section', 'technical descent'],
        trailheadLat: 40.6420,
        trailheadLng: -111.7480,
        trailheadAddress: 'Mill D Trailhead, Big Cottonwood Canyon, UT',
        route: [
          [40.6420, -111.7480], [40.6435, -111.7462], [40.6450, -111.7445],
          [40.6465, -111.7428], [40.6480, -111.7410], [40.6495, -111.7395],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 77,
        dataNote: 'Moderate-good confidence. Trail is shared with hikers — be courteous and yield.',
        surface: 'mixed',
        bestMonths: [6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // WASATCH CREST — Park City / Big Cottonwood
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'wasatch-crest',
    name: 'Wasatch Crest Trail',
    city: 'Park City / SLC',
    region: 'Wasatch Back',
    lat: 40.6650,
    lng: -111.6200,
    description: 'One of the most famous mountain bike trails in the country. Rides along the high ridge between Park City and the SLC canyons with jaw-dropping 360° views. Point-to-point — requires a car shuttle. Often snowbound until July.',
    parkingLat: 40.6650,
    parkingLng: -111.6200,
    parkingAddress: 'Guardsman Pass Rd, Big Cottonwood Canyon, UT (upper trailhead)',
    trails: [
      {
        id: 'wasatch-crest-main',
        name: 'Wasatch Crest Trail',
        difficulty: 'advanced',
        direction: 'one-way',
        lengthMiles: 16.5,
        elevationGainFt: 2200,
        estimatedTimeMin: 240,
        description: 'The crown jewel of Utah mountain biking. A high-alpine ridge traverse with sections above 10,000 feet. Spectacular views in every direction. Exposed to afternoon thunderstorms — start early. Physically demanding with technical sections.',
        howToRide: 'Shuttle one car to the Scott\'s Pass / Pinebrook exit off I-80. Drive second car to Guardsman Pass. Ride from Guardsman northeast along the ridge. The trail undulates constantly — no flat sections. Several narrow, exposed ridge sections require confidence. Descend via Scott\'s Pass to the bottom.',
        features: ['alpine', 'exposed ridge', 'high altitude', 'technical sections', 'water crossings', 'shuttle required', 'rocky', 'views'],
        trailheadLat: 40.6650,
        trailheadLng: -111.6200,
        trailheadAddress: 'Guardsman Pass, UT (start) — Scott\'s Pass, Park City, UT (end)',
        route: [
          [40.6650, -111.6200], [40.6662, -111.6152], [40.6675, -111.6102],
          [40.6688, -111.6050], [40.6700, -111.5998], [40.6712, -111.5945],
          [40.6725, -111.5892], [40.6738, -111.5840], [40.6750, -111.5788],
          [40.6762, -111.5735], [40.6775, -111.5682],
        ],
        dataSource: 'trailforks',
        dataConfidence: 91,
        dataNote: 'Very high confidence. One of Utah\'s most-reported trails. Check snow conditions before late June.',
        surface: 'alpine rocky',
        bestMonths: [7, 8, 9],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // EMIGRATION CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'emigration-canyon',
    name: 'Emigration Canyon',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.7480,
    lng: -111.7800,
    description: 'A classic road cycling canyon that also has some excellent MTB singletrack options above the canyon floor. Accessible directly from SLC\'s east side. Less crowded than Millcreek or Big Cottonwood.',
    parkingLat: 40.7480,
    parkingLng: -111.7800,
    parkingAddress: 'Emigration Canyon Rd, Salt Lake City, UT 84108',
    trails: [
      {
        id: 'little-mountain',
        name: 'Little Mountain Summit',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 5.2,
        elevationGainFt: 1050,
        estimatedTimeMin: 75,
        description: 'A consistent climb to the Little Mountain summit with panoramic views of both SLC and the Wasatch Back. Rocky in the upper section. One of the best value rides in the area — close to the city and very rewarding.',
        howToRide: 'Park at the Emigration Canyon mouth. Follow the road up a short distance then turn onto the signed singletrack. The climb is steady — find your pace and keep a consistent cadence. The final push to the summit is rocky but worth it for the 360° view.',
        features: ['rocky upper section', 'panoramic views', 'steady climb', 'technical summit'],
        trailheadLat: 40.7495,
        trailheadLng: -111.7762,
        trailheadAddress: 'Emigration Canyon Mouth Trailhead, SLC, UT',
        route: [
          [40.7495, -111.7762], [40.7508, -111.7740], [40.7522, -111.7718],
          [40.7535, -111.7695], [40.7548, -111.7672], [40.7562, -111.7650],
        ],
        dataSource: 'trailforks',
        dataConfidence: 79,
        dataNote: 'Moderate confidence. Trail conditions vary — can be dusty in summer, muddy in spring.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // UTAH VALLEY: AMERICAN FORK CANYON — Tibble Fork
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'american-fork-canyon',
    name: 'American Fork Canyon',
    city: 'American Fork',
    region: 'Utah Valley',
    lat: 40.4523,
    lng: -111.7617,
    description: 'A beautiful canyon south of SLC offering excellent intermediate singletrack among aspen groves and pine forests. The Tibble Fork Reservoir area is the main hub — accessible via US-92 (Alpine Loop). Entry fee required in summer. Stunning fall colors in September.',
    parkingLat: 40.4523,
    parkingLng: -111.7617,
    parkingAddress: 'Tibble Fork Trailhead, American Fork Canyon, UT 84003',
    trails: [
      {
        id: 'frank-trail',
        name: 'Frank',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 7.2,
        elevationGainFt: 1150,
        estimatedTimeMin: 90,
        description: "Frank is one of Utah's most celebrated intermediate trails — a perfectly designed loop through aspen and pine forest near Tibble Fork Reservoir. The trail is well-maintained, consistently fun, and rarely disappointing. A must-ride for any SLC-area mountain biker.",
        howToRide: 'Park at Tibble Fork Reservoir. Follow the signed Frank Trail junction from the trailhead. The loop climbs steadily through aspens then delivers a long, flowing descent back to the start. Ride clockwise — the descent flows better that direction. The trail is smooth with occasional rooted sections.',
        features: ['aspen forest', 'flowing singletrack', 'well-maintained', 'classic loop', 'smooth descent'],
        trailheadLat: 40.4523,
        trailheadLng: -111.7617,
        trailheadAddress: 'Tibble Fork Trailhead, American Fork Canyon, UT',
        route: [
          [40.4523, -111.7617], [40.4540, -111.7598], [40.4558, -111.7580],
          [40.4575, -111.7565], [40.4590, -111.7548], [40.4580, -111.7530],
          [40.4562, -111.7545], [40.4545, -111.7560], [40.4523, -111.7617],
        ],
        dataSource: 'trailforks',
        dataConfidence: 95,
        dataNote: "Very high confidence. Frank Trail is one of Utah's most-reviewed trails across all platforms.",
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'tibble-fork-loop',
        name: 'Tibble Fork Loop',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 3.2,
        elevationGainFt: 280,
        estimatedTimeMin: 35,
        description: 'A short, mellow loop circling Tibble Fork Reservoir through pine forest. Great for beginners visiting American Fork Canyon for the first time or as a warm-up lap before Frank Trail. The lakeside sections are especially scenic.',
        howToRide: 'From Tibble Fork parking area, follow the reservoir shoreline trail. The loop circles the reservoir on mostly flat doubletrack and singletrack. Very few technical features — ideal for new riders building confidence. The north side has a short uphill that beginners can walk if needed.',
        features: ['lakeside views', 'pine forest', 'minimal obstacles', 'scenic', 'family-friendly'],
        trailheadLat: 40.4510,
        trailheadLng: -111.7630,
        trailheadAddress: 'Tibble Fork Reservoir, American Fork Canyon, UT',
        route: [
          [40.4510, -111.7630], [40.4520, -111.7615], [40.4532, -111.7602],
          [40.4528, -111.7588], [40.4515, -111.7595], [40.4505, -111.7610],
          [40.4510, -111.7630],
        ],
        dataSource: 'trailforks',
        dataConfidence: 80,
        dataNote: 'Good confidence. Well-visited reservoir loop with consistent trail reports.',
        surface: 'smooth hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SOUTHEAST UTAH: MOAB — World-Class Slickrock
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'moab',
    name: 'Moab',
    city: 'Moab',
    region: 'Southeast Utah',
    lat: 38.5733,
    lng: -109.5498,
    description: "Moab is the mountain biking capital of the world — iconic red-rock slickrock, dramatic canyon views, and trails unlike anything else on earth. A 4-hour drive from SLC but worth every mile. Plan at least 2–3 days. Best ridden Oct–Nov and Mar–Apr; summer is extremely hot.",
    parkingLat: 38.5668,
    parkingLng: -109.5310,
    parkingAddress: 'Sand Flats Recreation Area, 1290 Sand Flats Rd, Moab, UT 84532',
    trails: [
      {
        id: 'slickrock-bike-trail',
        name: 'Slickrock Bike Trail',
        difficulty: 'advanced',
        direction: 'loop',
        lengthMiles: 10.5,
        elevationGainFt: 1800,
        estimatedTimeMin: 180,
        description: "The most famous mountain bike trail on earth. Slickrock is a 10.5-mile loop over undulating Navajo sandstone with zero trees, near-infinite views of canyon country, and a traction level you have to experience to believe. The rock surface grips your tires like velcro — but the exposure and steep roll-ins demand respect. A bucket-list ride.",
        howToRide: 'Start at the Sand Flats Recreation Area ($5 entry fee). A short 2.3-mile practice loop near the trailhead is mandatory for first-timers — ride it before the main loop. The main loop follows white painted dashes on the rock. Go slowly on the steep drop-ins — the rock grips well but there is no bail-out. Bring 3+ liters of water, food, and sun protection. Best done with a partner.',
        features: ['Navajo sandstone', 'canyon views', 'painted route markers', 'zero trees', 'bucket-list', 'exposed'],
        trailheadLat: 38.5685,
        trailheadLng: -109.5305,
        trailheadAddress: 'Sand Flats Recreation Area, Moab, UT 84532',
        route: [
          [38.5685, -109.5305], [38.5705, -109.5280], [38.5725, -109.5255],
          [38.5745, -109.5232], [38.5760, -109.5210], [38.5748, -109.5188],
          [38.5728, -109.5205], [38.5710, -109.5228], [38.5695, -109.5260],
          [38.5685, -109.5305],
        ],
        dataSource: 'trailforks',
        dataConfidence: 98,
        dataNote: 'Extremely high confidence. Slickrock is one of the most documented trails in the world.',
        surface: 'Navajo sandstone',
        bestMonths: [3, 4, 10, 11],
      },
      {
        id: 'bar-m-loop',
        name: 'Bar M Loop',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 7.8,
        elevationGainFt: 350,
        estimatedTimeMin: 75,
        description: "Moab's best beginner trail — a wide, smooth loop through classic red-rock desert terrain north of town. Bar M gives first-time Moab visitors a taste of Utah's canyon country without technical demands. Stunning scenery on an approachable route.",
        howToRide: "Start from the Klondike Bluffs area parking. Bar M Loop is wide and well-marked — follow the main track through the desert. There are a couple of optional rock features you can skip entirely. Great for taking photos and soaking in the red-rock landscape. No significant climbs.",
        features: ['wide smooth track', 'desert scenery', 'red rock', 'beginner-friendly', 'great photos'],
        trailheadLat: 38.6387,
        trailheadLng: -109.6058,
        trailheadAddress: 'Bar M Trailhead, Moab, UT 84532',
        route: [
          [38.6387, -109.6058], [38.6405, -109.6038], [38.6422, -109.6018],
          [38.6435, -109.6000], [38.6420, -109.5980], [38.6402, -109.5998],
          [38.6387, -109.6058],
        ],
        dataSource: 'trailforks',
        dataConfidence: 92,
        dataNote: 'Very high confidence. Popular beginner Moab trail well-documented on AllTrails and Trailforks.',
        surface: 'hardpack sand/dirt',
        bestMonths: [3, 4, 5, 9, 10, 11],
      },
      {
        id: 'sovereign-trail',
        name: 'Sovereign Trail',
        difficulty: 'intermediate',
        direction: 'one-way',
        lengthMiles: 14.8,
        elevationGainFt: 1200,
        estimatedTimeMin: 150,
        description: "A long, dramatic singletrack traverse through pinyon-juniper desert north of Moab. Sovereign Trail is loved for its remote feel, technical rock moves, and variety — you'll encounter slickrock crossings, loose desert dirt, and exposed ledges all on one ride. Best done as a point-to-point with a car shuttle.",
        howToRide: 'Shuttle a car to the Hideout Canyon trailhead. Start from the Klondike Bluffs area. The trail flows through desert terrain with occasional technical rock sections — most are rideable by solid intermediates but have walk-around options. Bring plenty of water; the trail is exposed for most of its length.',
        features: ['desert singletrack', 'rock moves', 'remote', 'exposed', 'point-to-point', 'technical sections'],
        trailheadLat: 38.6527,
        trailheadLng: -109.6423,
        trailheadAddress: 'Klondike Bluffs Trailhead, Moab, UT 84532',
        route: [
          [38.6527, -109.6423], [38.6510, -109.6398], [38.6490, -109.6370],
          [38.6468, -109.6342], [38.6445, -109.6315], [38.6420, -109.6288],
          [38.6395, -109.6262],
        ],
        dataSource: 'trailforks',
        dataConfidence: 90,
        dataNote: 'High confidence. Sovereign Trail is well-documented across Trailforks and MTB Project.',
        surface: 'desert hardpack / slickrock',
        bestMonths: [3, 4, 10, 11],
      },
      {
        id: 'klondike-bluffs',
        name: 'Klondike Bluffs',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 9.2,
        elevationGainFt: 950,
        estimatedTimeMin: 110,
        description: 'A stunning loop on the red bluffs north of Moab featuring a mix of smooth desert singletrack, slickrock domes, and technical rocky sections. Klondike Bluffs is less crowded than Slickrock and offers a more varied riding experience. You can even see dinosaur tracks near the trailhead.',
        howToRide: 'Park at the Klondike Bluffs trailhead off US-191 north of Moab. Follow the main track out to the bluffs — the optional slickrock sections are marked. The return leg has the best views. Technical sections can be walked. Check for dinosaur tracks in the sandstone near the parking area (really!).',
        features: ['slickrock domes', 'desert views', 'less crowded', 'technical optional', 'dinosaur tracks'],
        trailheadLat: 38.6527,
        trailheadLng: -109.6423,
        trailheadAddress: 'Klondike Bluffs Trailhead, US-191 N, Moab, UT',
        route: [
          [38.6527, -109.6423], [38.6545, -109.6405], [38.6562, -109.6385],
          [38.6575, -109.6362], [38.6560, -109.6342], [38.6542, -109.6362],
          [38.6527, -109.6423],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'High confidence. Popular Moab trail with consistent AllTrails and Trailforks reports.',
        surface: 'desert hardpack / slickrock',
        bestMonths: [3, 4, 10, 11],
      },
    ],
  },

]

// ─────────────────────────────────────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

// Flatten all trails into a single array (useful for search, distance calc)
export function getAllTrails() {
  return trailAreas.flatMap(area =>
    area.trails.map(trail => ({
      ...trail,
      area: area.name,
      areaId: area.id,
      city: area.city,
      region: area.region,
    }))
  )
}

// Get a single area by ID
export function getAreaById(id) {
  return trailAreas.find(area => area.id === id)
}

// Get a single trail with full context (including area's parking coords)
export function getTrailById(areaId, trailId) {
  const area = getAreaById(areaId)
  if (!area) return null
  const trail = area.trails.find(t => t.id === trailId)
  if (!trail) return null
  return {
    ...trail,
    area: area.name,
    areaId: area.id,
    city: area.city,
    region: area.region,
    parkingLat: area.parkingLat,
    parkingLng: area.parkingLng,
    parkingAddress: area.parkingAddress,
    // Pass all sibling trails so the detail page can show the area trail map
    siblingTrails: area.trails,
  }
}

// Difficulty color + label mapping — used across the UI
export const difficultyConfig = {
  beginner:     { label: 'Beginner',     color: 'bg-green-100 text-green-800',  dot: 'bg-green-500'  },
  intermediate: { label: 'Intermediate', color: 'bg-yellow-100 text-yellow-800', dot: 'bg-yellow-500' },
  advanced:     { label: 'Advanced',     color: 'bg-red-100 text-red-800',      dot: 'bg-red-500'    },
}
