// lib/trails.js
// Utah MTB trail data — organized by area (parent) → trails (children).
// Each area has GPS coordinates and each trail has approximate route polylines
// for map highlighting. Route coordinates are approximate, not precise GPX data.
// Data sourced/cross-referenced from Trailforks, MTB Project, and local knowledge.

export const trailAreas = [

  // ─────────────────────────────────────────────────────────────────────────
  // SLC SOUTH: CORNER CANYON — Draper
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'corner-canyon',
    name: 'Corner Canyon',
    city: 'Draper',
    region: 'Salt Lake Valley',
    lat: 40.4677,
    lng: -111.8580,
    description: 'One of the most popular riding destinations in Utah with a huge trail network for all skill levels. Located in the southeast corner of the Salt Lake Valley. Trails range from smooth beginner loops to technical rocky descents.',
    parkingLat: 40.4677,
    parkingLng: -111.8580,
    parkingAddress: '14800 Corner Canyon Rd, Draper, UT 84020',
    trails: [
      {
        id: 'chutes-and-ladders',
        name: 'Chutes & Ladders',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 5.2,
        elevationGainFt: 650,
        estimatedTimeMin: 60,
        description: 'A classic beginner loop at Corner Canyon. Smooth singletrack with gentle climbs and fun swoopy descents. Great first trail for new mountain bikers. Well-marked and easy to navigate.',
        howToRide: 'Start at the Hammond Canyon trailhead. Follow the signs for Chutes & Ladders. Ride clockwise for the best flow. The loop is well-marked — take the lower connector back to the parking area. Watch for hikers on weekends.',
        features: ['smooth singletrack', 'beginner-friendly berms', 'some roots', 'well-marked'],
        trailheadLat: 40.4681,
        trailheadLng: -111.8562,
        trailheadAddress: 'Hammond Canyon Trailhead, Draper, UT',
        // Approximate route polyline for map display
        route: [
          [40.4681, -111.8562], [40.4690, -111.8555], [40.4702, -111.8548],
          [40.4710, -111.8540], [40.4715, -111.8530], [40.4708, -111.8520],
          [40.4698, -111.8525], [40.4688, -111.8535], [40.4681, -111.8545],
          [40.4681, -111.8562],
        ],
        dataSource: 'trailforks',
        dataConfidence: 85,
        dataNote: 'Trail data sourced from Trailforks community reports. Length and elevation verified. Conditions may vary seasonally.',
        surface: 'smooth hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'ghost-falls',
        name: 'Ghost Falls',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 7.8,
        elevationGainFt: 1200,
        estimatedTimeMin: 90,
        description: 'A rewarding intermediate trail with a sustained climb and fast descent. Features a waterfall viewpoint about halfway up. Rocky in sections. One of the most iconic trails in Corner Canyon.',
        howToRide: 'Climb up via the Ghost Falls trail from the south trailhead. The first mile is the steepest — pace yourself. At the top, enjoy the views before descending the same way. Watch for sharp switchbacks on the way down. Rocky lower section requires attention.',
        features: ['rocky sections', 'waterfall viewpoint', 'steep climb', 'fast descent', 'sharp curves'],
        trailheadLat: 40.4710,
        trailheadLng: -111.8540,
        trailheadAddress: 'Ghost Falls Trailhead, Draper, UT',
        route: [
          [40.4710, -111.8540], [40.4720, -111.8530], [40.4732, -111.8518],
          [40.4745, -111.8505], [40.4758, -111.8492], [40.4770, -111.8480],
          [40.4782, -111.8470], [40.4795, -111.8460],
        ],
        dataSource: 'trailforks',
        dataConfidence: 90,
        dataNote: 'High confidence — frequently reported trail with consistent data from multiple sources.',
        surface: 'rocky hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'ann-canyon',
        name: 'Ann Canyon',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 6.1,
        elevationGainFt: 900,
        estimatedTimeMin: 75,
        description: 'A flowy intermediate loop connecting several trails through Ann Canyon. Known for fun berms and occasional technical rock sections. Mixes smooth and rough terrain nicely.',
        howToRide: 'Start at the Corner Canyon main trailhead. Head up the fire road to the canyon entrance, then follow Ann Canyon trail counterclockwise for the best flow on the descent. The upper section has some technical rock moves.',
        features: ['berms', 'rocky sections', 'technical features', 'some jumps'],
        trailheadLat: 40.4695,
        trailheadLng: -111.8570,
        trailheadAddress: 'Corner Canyon Main Trailhead, Draper, UT',
        route: [
          [40.4695, -111.8570], [40.4705, -111.8558], [40.4718, -111.8545],
          [40.4728, -111.8532], [40.4720, -111.8520], [40.4708, -111.8530],
          [40.4695, -111.8545], [40.4695, -111.8570],
        ],
        dataSource: 'trailforks',
        dataConfidence: 80,
        dataNote: 'Data sourced from Trailforks. Some sections under periodic trail maintenance.',
        surface: 'loose over hard',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'clarks-trail',
        name: "Clark's Trail",
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 8.4,
        elevationGainFt: 1100,
        estimatedTimeMin: 90,
        description: "One of Corner Canyon's most popular trails. A mix of smooth singletrack and technical features with a great flow section on the descent. Connects to multiple other trails in the network.",
        howToRide: "Start at Hammond Canyon trailhead and follow signs for Clark's. The climb is gradual until the upper switchbacks. Descend the main Clark's line — it has a few optional jump features you can roll around. Finish loops back to the main trailhead.",
        features: ['optional jumps', 'berms', 'switchbacks', 'technical upper section', 'fast descent'],
        trailheadLat: 40.4685,
        trailheadLng: -111.8556,
        trailheadAddress: 'Hammond Canyon Trailhead, Draper, UT',
        route: [
          [40.4685, -111.8556], [40.4698, -111.8542], [40.4712, -111.8528],
          [40.4725, -111.8515], [40.4738, -111.8500], [40.4748, -111.8488],
          [40.4738, -111.8480], [40.4722, -111.8495], [40.4710, -111.8510],
          [40.4698, -111.8525], [40.4685, -111.8556],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'Very well-documented trail. Trailforks and MTB Project data align closely.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'potato-hill',
        name: 'Potato Hill',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 3.5,
        elevationGainFt: 350,
        estimatedTimeMin: 40,
        description: 'A short, mellow loop that is perfect for first-time riders or warm-up laps. Smooth dirt with minimal obstacles. Offers great views of the Salt Lake Valley without committing to a long ride.',
        howToRide: 'Park at the Corner Canyon trailhead. Follow the wide path north toward Potato Hill. The loop circles the small hill and offers great views. Ride it multiple times for a longer workout — it\'s a great option for building fitness.',
        features: ['smooth dirt', 'beginner-friendly', 'valley views', 'short loop'],
        trailheadLat: 40.4670,
        trailheadLng: -111.8575,
        trailheadAddress: 'Corner Canyon Trailhead, Draper, UT',
        route: [
          [40.4670, -111.8575], [40.4678, -111.8565], [40.4685, -111.8558],
          [40.4680, -111.8548], [40.4670, -111.8555], [40.4665, -111.8565],
          [40.4670, -111.8575],
        ],
        dataSource: 'trailforks',
        dataConfidence: 82,
        dataNote: 'Moderate-high confidence. Beginner trail with consistent community reports.',
        surface: 'smooth hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10, 11],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SLC EAST: MILLCREEK CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'millcreek-canyon',
    name: 'Millcreek Canyon',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.6868,
    lng: -111.7560,
    description: 'A beloved canyon just 20 minutes from downtown SLC. Offers everything from mellow doubletrack to expert-level singletrack. Dogs allowed on even-numbered days. Fee required for vehicles.',
    parkingLat: 40.6868,
    parkingLng: -111.7560,
    parkingAddress: 'Millcreek Canyon Rd, Salt Lake City, UT 84109',
    trails: [
      {
        id: 'big-water-trail',
        name: 'Big Water Trail',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 8.2,
        elevationGainFt: 1500,
        estimatedTimeMin: 120,
        description: 'A sustained climb up a beautiful canyon with a rewarding descent. Mostly hardpacked dirt with some rocky and rooty sections near the top. A Millcreek classic.',
        howToRide: 'Park at the upper Millcreek trailhead. Head up the fire road, then transition to singletrack. The trail follows the creek for the first mile before climbing steeply. Turn around at the ridge or continue to connect with Wasatch Crest Trail.',
        features: ['creek crossings', 'rocky upper section', 'rooty lower section', 'sustained climb'],
        trailheadLat: 40.6910,
        trailheadLng: -111.7450,
        trailheadAddress: 'Upper Millcreek Trailhead, SLC, UT',
        route: [
          [40.6910, -111.7450], [40.6920, -111.7438], [40.6932, -111.7422],
          [40.6945, -111.7405], [40.6958, -111.7390], [40.6972, -111.7375],
          [40.6985, -111.7362], [40.7000, -111.7350],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 82,
        dataNote: 'Data sourced from MTB Project. Trail conditions can be wet in spring — check recent reports.',
        surface: 'mixed rocky',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'pipeline-trail',
        name: 'Pipeline Trail',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 3.8,
        elevationGainFt: 200,
        estimatedTimeMin: 40,
        description: 'A flat-to-gentle trail following an old water pipeline route. Excellent for beginners or a casual pedal. Great views of the Salt Lake Valley and Millcreek canyon mouth.',
        howToRide: 'Access from the lower Millcreek trailhead. The trail is mostly flat and follows the pipeline grade. Suitable for all fitness levels. Can be ridden as an out-and-back or combined with other trails for a longer loop.',
        features: ['flat', 'valley views', 'beginner-friendly', 'well-maintained'],
        trailheadLat: 40.6875,
        trailheadLng: -111.7520,
        trailheadAddress: 'Lower Millcreek Trailhead, SLC, UT',
        route: [
          [40.6875, -111.7520], [40.6882, -111.7505], [40.6890, -111.7490],
          [40.6898, -111.7475], [40.6905, -111.7460], [40.6910, -111.7450],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 78,
        dataNote: 'Moderate confidence. MTB Project data cross-referenced with local trail reports.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'alexander-basin',
        name: 'Alexander Basin Trail',
        difficulty: 'advanced',
        direction: 'out-and-back',
        lengthMiles: 5.8,
        elevationGainFt: 1800,
        estimatedTimeMin: 100,
        description: 'A challenging alpine climb into a stunning glacial basin. Technical rocky sections and loose dirt on the upper trail. The views at the top are some of the best in the Wasatch. Not for beginners.',
        howToRide: 'Head up Millcreek Canyon road to the Alexander Basin trailhead near the canyon end. The trail starts mellow then becomes progressively steeper and rockier. The upper basin has loose rock — keep your momentum and pick smooth lines. Save energy for the final steep push to the ridge.',
        features: ['rocky', 'alpine views', 'steep climb', 'loose upper section', 'technical'],
        trailheadLat: 40.7050,
        trailheadLng: -111.7280,
        trailheadAddress: 'Alexander Basin Trailhead, Millcreek Canyon, UT',
        route: [
          [40.7050, -111.7280], [40.7065, -111.7262], [40.7080, -111.7245],
          [40.7095, -111.7228], [40.7110, -111.7210], [40.7125, -111.7195],
        ],
        dataSource: 'trailforks',
        dataConfidence: 75,
        dataNote: 'Moderate confidence. Less-documented trail — verify current conditions with local riders before attempting.',
        surface: 'technical rocky',
        bestMonths: [6, 7, 8, 9],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // WASATCH BACK: ROUND VALLEY — Park City
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'round-valley',
    name: 'Round Valley',
    city: 'Park City',
    region: 'Wasatch Back',
    lat: 40.6461,
    lng: -111.4980,
    description: 'A network of cross-country trails just minutes from downtown Park City. Known for incredible views, smooth singletrack, and beginner-friendly routes that connect to more advanced terrain. One of Utah\'s best all-around trail systems.',
    parkingLat: 40.6461,
    parkingLng: -111.4980,
    parkingAddress: 'Round Valley Trailhead, Park City, UT 84060',
    trails: [
      {
        id: 'round-valley-express',
        name: 'Round Valley Express',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 4.5,
        elevationGainFt: 400,
        estimatedTimeMin: 45,
        description: 'The quintessential beginner trail in Park City. Smooth, flowy singletrack with minimal technical sections. Perfect for building confidence and fitness. Stunning views of the Wasatch range.',
        howToRide: 'Start at the Round Valley trailhead off Bitner Road. Follow the green (easy) markers. The loop is mostly flat with one small climb near the midpoint. Excellent views of the Wasatch range throughout.',
        features: ['smooth singletrack', 'beginner-friendly', 'mountain views', 'well-marked'],
        trailheadLat: 40.6465,
        trailheadLng: -111.4975,
        trailheadAddress: 'Round Valley Trailhead, Bitner Rd, Park City, UT',
        route: [
          [40.6465, -111.4975], [40.6475, -111.4960], [40.6488, -111.4945],
          [40.6498, -111.4932], [40.6492, -111.4918], [40.6480, -111.4925],
          [40.6470, -111.4938], [40.6462, -111.4952], [40.6465, -111.4975],
        ],
        dataSource: 'trailforks',
        dataConfidence: 92,
        dataNote: 'Very high confidence. One of the most documented trails in Utah with consistent community reporting.',
        surface: 'smooth hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'round-valley-west',
        name: 'Round Valley West',
        difficulty: 'beginner',
        direction: 'loop',
        lengthMiles: 5.1,
        elevationGainFt: 480,
        estimatedTimeMin: 55,
        description: 'The western extension of the Round Valley trail network. Similar character to Round Valley Express — smooth and flowing with gentle grades. Great for longer beginner sessions or back-to-back loops.',
        howToRide: 'From the Round Valley trailhead, head west on the signed connector. The trail winds through open meadows and sparse pines. Very few obstacles — focus on building your rhythm and pedaling efficiency.',
        features: ['smooth singletrack', 'open meadows', 'gentle grades', 'beginner-friendly'],
        trailheadLat: 40.6455,
        trailheadLng: -111.5020,
        trailheadAddress: 'Round Valley West Trailhead, Park City, UT',
        route: [
          [40.6455, -111.5020], [40.6462, -111.5038], [40.6472, -111.5055],
          [40.6480, -111.5042], [40.6475, -111.5025], [40.6465, -111.5015],
          [40.6455, -111.5020],
        ],
        dataSource: 'trailforks',
        dataConfidence: 85,
        dataNote: 'High confidence. Well-maintained Park City trail with good community data.',
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
      {
        id: 'mid-mountain',
        name: 'Mid-Mountain Trail',
        difficulty: 'intermediate',
        direction: 'one-way',
        lengthMiles: 14.3,
        elevationGainFt: 1800,
        estimatedTimeMin: 180,
        description: 'An epic point-to-point trail traversing the mid-mountain zone above Park City. Connects multiple ski resorts with stunning alpine views. One of Utah\'s most celebrated MTB trails. Requires a car shuttle or ride back.',
        howToRide: 'Start at the Glenwild trailhead and ride east toward Park City Mountain. This is a one-way trail — plan for a shuttle. The trail undulates significantly; several long climbs offset by beautiful descents. Take the Deer Valley cutoff for a shorter version.',
        features: ['alpine views', 'technical sections', 'water crossings', 'rocky', 'exposed ridge', 'long distance'],
        trailheadLat: 40.6830,
        trailheadLng: -111.5640,
        trailheadAddress: 'Glenwild Trailhead, Park City, UT',
        route: [
          [40.6830, -111.5640], [40.6818, -111.5580], [40.6805, -111.5520],
          [40.6792, -111.5460], [40.6778, -111.5400], [40.6762, -111.5340],
          [40.6748, -111.5280], [40.6732, -111.5220], [40.6718, -111.5160],
          [40.6700, -111.5100], [40.6685, -111.5042],
        ],
        dataSource: 'trailforks',
        dataConfidence: 88,
        dataNote: 'Data confidence high for main corridor. Some connecting spur trails may have limited data.',
        surface: 'mixed',
        bestMonths: [6, 7, 8, 9, 10],
      },
      {
        id: 'sweeney-switchbacks',
        name: 'Sweeney Switchbacks',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 4.8,
        elevationGainFt: 980,
        estimatedTimeMin: 70,
        description: 'A series of tight, technical switchbacks that climbs sharply above Park City. Challenging climbing with a fast, flowy descent. Tests your technical skills and fitness in equal measure.',
        howToRide: 'Access from the lower Round Valley trailhead. Follow the connector to Sweeney. The switchbacks require momentum management — stay loose and keep pedaling. The descent rewards your effort: fast and sweeping with great views of the valley.',
        features: ['tight switchbacks', 'technical climbing', 'fast descent', 'mountain views'],
        trailheadLat: 40.6440,
        trailheadLng: -111.4965,
        trailheadAddress: 'Round Valley Lower Trailhead, Park City, UT',
        route: [
          [40.6440, -111.4965], [40.6448, -111.4952], [40.6456, -111.4940],
          [40.6464, -111.4928], [40.6472, -111.4915], [40.6480, -111.4902],
          [40.6488, -111.4892],
        ],
        dataSource: 'trailforks',
        dataConfidence: 83,
        dataNote: 'Good confidence. Popular Park City trail well-reported on Trailforks.',
        surface: 'hardpack',
        bestMonths: [5, 6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SLC FOOTHILLS: BONNEVILLE SHORELINE TRAIL
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'bonneville-shoreline',
    name: 'Bonneville Shoreline Trail',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.7484,
    lng: -111.8280,
    description: 'A long traversing trail following the ancient shoreline of Lake Bonneville along the base of the Wasatch Mountains. Accessible from many SLC neighborhoods — one of the most accessible trail systems in the valley.',
    parkingLat: 40.7484,
    parkingLng: -111.8280,
    parkingAddress: 'Various access points along Wasatch Blvd, SLC, UT',
    trails: [
      {
        id: 'bst-north',
        name: 'BST North (City Creek to Red Butte)',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 6.5,
        elevationGainFt: 600,
        estimatedTimeMin: 75,
        description: 'The northern section of the iconic Bonneville Shoreline Trail. Gentle grade with incredible views of the Salt Lake Valley. A local favorite for after-work rides. Very accessible from multiple SLC neighborhoods.',
        howToRide: 'Start at City Creek Canyon trailhead. Head north along the bench. The trail undulates gently with a few short hike-a-bike sections. End at Red Butte Garden for a natural turnaround, or continue south toward the U of U.',
        features: ['city views', 'some loose gravel', 'exposed hillside', 'beginner-friendly'],
        trailheadLat: 40.7730,
        trailheadLng: -111.8640,
        trailheadAddress: 'City Creek Canyon Trailhead, SLC, UT',
        route: [
          [40.7730, -111.8640], [40.7715, -111.8618], [40.7698, -111.8595],
          [40.7682, -111.8572], [40.7665, -111.8550], [40.7648, -111.8528],
          [40.7632, -111.8505],
        ],
        dataSource: 'trailforks',
        dataConfidence: 75,
        dataNote: 'Moderate confidence. BST is maintained by volunteers — conditions vary by section.',
        surface: 'hardpack',
        bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
      },
      {
        id: 'bst-south',
        name: 'BST South (Emigration to Neff\'s)',
        difficulty: 'beginner',
        direction: 'one-way',
        lengthMiles: 7.2,
        elevationGainFt: 700,
        estimatedTimeMin: 85,
        description: 'The southern section of the BST, connecting Emigration Canyon to Neff\'s Canyon. More technical than the north section with some rocky patches. Gets you into wilder terrain while still being close to the city.',
        howToRide: 'Start at the Emigration Canyon trailhead. Head south following the Bonneville shoreline contour. The trail rolls along the hillside with some short rocky sections. Ends at the Neff\'s Canyon parking area — great shuttle option.',
        features: ['rocky sections', 'valley views', 'some technical spots', 'shuttle-friendly'],
        trailheadLat: 40.7480,
        trailheadLng: -111.8050,
        trailheadAddress: 'Emigration Canyon Trailhead, SLC, UT',
        route: [
          [40.7480, -111.8050], [40.7462, -111.8025], [40.7445, -111.8000],
          [40.7428, -111.7978], [40.7410, -111.7955], [40.7392, -111.7932],
        ],
        dataSource: 'trailforks',
        dataConfidence: 72,
        dataNote: 'Moderate confidence. Conditions vary — check Salt Lake Trails Alliance for current status.',
        surface: 'hardpack',
        bestMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BIG COTTONWOOD CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'big-cottonwood',
    name: 'Big Cottonwood Canyon',
    city: 'Sandy / Cottonwood Heights',
    region: 'Wasatch Front',
    lat: 40.6350,
    lng: -111.7800,
    description: 'A stunning canyon southeast of SLC with high-alpine trails. Home to Solitude and Brighton ski resorts in winter, converted to excellent MTB terrain in summer. Expect cooler temperatures and spectacular alpine scenery.',
    parkingLat: 40.6350,
    parkingLng: -111.7800,
    parkingAddress: 'Big Cottonwood Canyon Rd, Cottonwood Heights, UT 84121',
    trails: [
      {
        id: 'bcc-storm-mountain',
        name: 'Storm Mountain Trail',
        difficulty: 'intermediate',
        direction: 'loop',
        lengthMiles: 5.5,
        elevationGainFt: 1100,
        estimatedTimeMin: 80,
        description: 'A popular canyon trail with a mix of technical rock features and smooth singletrack. Scenic views of the canyon walls throughout. Gets busy on summer weekends — go early.',
        howToRide: 'Park at the Storm Mountain picnic area. Follow the signed trail upstream before climbing steeply. The technical rocky section at mid-trail is the crux — take the bypass if unsure. Great descent back to the trailhead.',
        features: ['rocky sections', 'canyon views', 'technical crux section', 'some roots'],
        trailheadLat: 40.6382,
        trailheadLng: -111.7698,
        trailheadAddress: 'Storm Mountain Picnic Area, Big Cottonwood Canyon, UT',
        route: [
          [40.6382, -111.7698], [40.6395, -111.7680], [40.6408, -111.7662],
          [40.6420, -111.7645], [40.6415, -111.7628], [40.6402, -111.7640],
          [40.6390, -111.7658], [40.6382, -111.7698],
        ],
        dataSource: 'trailforks',
        dataConfidence: 80,
        dataNote: 'Good confidence. Trailforks data verified with MTB Project cross-reference.',
        surface: 'rocky hardpack',
        bestMonths: [6, 7, 8, 9],
      },
      {
        id: 'bcc-mill-d-north',
        name: 'Mill D North Fork',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 6.8,
        elevationGainFt: 1400,
        estimatedTimeMin: 100,
        description: 'A classic canyon hike turned MTB route. Follows a beautiful creek drainage up to a scenic alpine meadow. Rocky in the upper section. Worth every pedal stroke for the views.',
        howToRide: 'Start at the Mill D trailhead (milepost 9 in BCC). Follow the creek drainage uphill. The lower trail is smooth and fun; the upper section gets rocky and loose. The meadow at the top is a great rest spot before the descent.',
        features: ['creek crossings', 'alpine meadow', 'rocky upper section', 'technical descent'],
        trailheadLat: 40.6420,
        trailheadLng: -111.7480,
        trailheadAddress: 'Mill D Trailhead, Big Cottonwood Canyon, UT',
        route: [
          [40.6420, -111.7480], [40.6435, -111.7462], [40.6450, -111.7445],
          [40.6465, -111.7428], [40.6480, -111.7410], [40.6495, -111.7395],
        ],
        dataSource: 'mtb-project',
        dataConfidence: 77,
        dataNote: 'Moderate-good confidence. Trail is shared with hikers — be courteous and yield.',
        surface: 'mixed',
        bestMonths: [6, 7, 8, 9, 10],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // WASATCH CREST — Park City / Big Cottonwood
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'wasatch-crest',
    name: 'Wasatch Crest Trail',
    city: 'Park City / SLC',
    region: 'Wasatch Back',
    lat: 40.6650,
    lng: -111.6200,
    description: 'One of the most famous mountain bike trails in the country. Rides along the high ridge between Park City and the SLC canyons with jaw-dropping 360° views. Point-to-point — requires a car shuttle. Often snowbound until July.',
    parkingLat: 40.6650,
    parkingLng: -111.6200,
    parkingAddress: 'Guardsman Pass Rd, Big Cottonwood Canyon, UT (upper trailhead)',
    trails: [
      {
        id: 'wasatch-crest-main',
        name: 'Wasatch Crest Trail',
        difficulty: 'advanced',
        direction: 'one-way',
        lengthMiles: 16.5,
        elevationGainFt: 2200,
        estimatedTimeMin: 240,
        description: 'The crown jewel of Utah mountain biking. A high-alpine ridge traverse with sections above 10,000 feet. Spectacular views in every direction. Exposed to afternoon thunderstorms — start early. Physically demanding with technical sections.',
        howToRide: 'Shuttle one car to the Scott\'s Pass / Pinebrook exit off I-80. Drive second car to Guardsman Pass. Ride from Guardsman northeast along the ridge. The trail undulates constantly — no flat sections. Several narrow, exposed ridge sections require confidence. Descend via Scott\'s Pass to the bottom.',
        features: ['alpine', 'exposed ridge', 'high altitude', 'technical sections', 'water crossings', 'shuttle required', 'rocky', 'views'],
        trailheadLat: 40.6650,
        trailheadLng: -111.6200,
        trailheadAddress: 'Guardsman Pass, UT (start) — Scott\'s Pass, Park City, UT (end)',
        route: [
          [40.6650, -111.6200], [40.6662, -111.6152], [40.6675, -111.6102],
          [40.6688, -111.6050], [40.6700, -111.5998], [40.6712, -111.5945],
          [40.6725, -111.5892], [40.6738, -111.5840], [40.6750, -111.5788],
          [40.6762, -111.5735], [40.6775, -111.5682],
        ],
        dataSource: 'trailforks',
        dataConfidence: 91,
        dataNote: 'Very high confidence. One of Utah\'s most-reported trails. Check snow conditions before late June.',
        surface: 'alpine rocky',
        bestMonths: [7, 8, 9],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // EMIGRATION CANYON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'emigration-canyon',
    name: 'Emigration Canyon',
    city: 'Salt Lake City',
    region: 'Wasatch Front',
    lat: 40.7480,
    lng: -111.7800,
    description: 'A classic road cycling canyon that also has some excellent MTB singletrack options above the canyon floor. Accessible directly from SLC\'s east side. Less crowded than Millcreek or Big Cottonwood.',
    parkingLat: 40.7480,
    parkingLng: -111.7800,
    parkingAddress: 'Emigration Canyon Rd, Salt Lake City, UT 84108',
    trails: [
      {
        id: 'little-mountain',
        name: 'Little Mountain Summit',
        difficulty: 'intermediate',
        direction: 'out-and-back',
        lengthMiles: 5.2,
        elevationGainFt: 1050,
        estimatedTimeMin: 75,
        description: 'A consistent climb to the Little Mountain summit with panoramic views of both SLC and the Wasatch Back. Rocky in the upper section. One of the best value rides in the area — close to the city and very rewarding.',
        howToRide: 'Park at the Emigration Canyon mouth. Follow the road up a short distance then turn onto the signed singletrack. The climb is steady — find your pace and keep a consistent cadence. The final push to the summit is rocky but worth it for the 360° view.',
        features: ['rocky upper section', 'panoramic views', 'steady climb', 'technical summit'],
        trailheadLat: 40.7495,
        trailheadLng: -111.7762,
        trailheadAddress: 'Emigration Canyon Mouth Trailhead, SLC, UT',
        route: [
          [40.7495, -111.7762], [40.7508, -111.7740], [40.7522, -111.7718],
          [40.7535, -111.7695], [40.7548, -111.7672], [40.7562, -111.7650],
        ],
        dataSource: 'trailforks',
        dataConfidence: 79,
        dataNote: 'Moderate confidence. Trail conditions vary — can be dusty in summer, muddy in spring.',
        surface: 'hardpack',
        bestMonths: [4, 5, 6, 7, 8, 9, 10],
      },
    ],
  },

]

// ─────────────────────────────────────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

// Flatten all trails into a single array (useful for search, distance calc)
export function getAllTrails() {
  return trailAreas.flatMap(area =>
    area.trails.map(trail => ({
      ...trail,
      area: area.name,
      areaId: area.id,
      city: area.city,
      region: area.region,
    }))
  )
}

// Get a single area by ID
export function getAreaById(id) {
  return trailAreas.find(area => area.id === id)
}

// Get a single trail with full context (including area's parking coords)
export function getTrailById(areaId, trailId) {
  const area = getAreaById(areaId)
  if (!area) return null
  const trail = area.trails.find(t => t.id === trailId)
  if (!trail) return null
  return {
    ...trail,
    area: area.name,
    areaId: area.id,
    city: area.city,
    region: area.region,
    parkingLat: area.parkingLat,
    parkingLng: area.parkingLng,
    parkingAddress: area.parkingAddress,
    // Pass all sibling trails so the detail page can show the area trail map
    siblingTrails: area.trails,
  }
}

// Difficulty color + label mapping — used across the UI
export const difficultyConfig = {
  beginner:     { label: 'Beginner',     color: 'bg-green-100 text-green-800',  dot: 'bg-green-500'  },
  intermediate: { label: 'Intermediate', color: 'bg-yellow-100 text-yellow-800', dot: 'bg-yellow-500' },
  advanced:     { label: 'Advanced',     color: 'bg-red-100 text-red-800',      dot: 'bg-red-500'    },
}
